version: '3'
services:
  api:
    image: srikars2001/fastapi:latest
    depends_on:
      - postgres
    ports:
      - "4000:8000"
    
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES} 

  postgres:
    image: postgres
    ports:
      - "6969:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:       