version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=srikars@2001888648512
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=srikar
      - SECRET_KEY=6118f54e8bf4c1ed1dc392098e67d0294019d0455a15bd83c5f65d711757e231
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60 

  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=srikars@2001888648512
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=srikar
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:       